import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import AnimatedLogo from "@/components/AnimatedLogo";
import MobileNav from "@/components/MobileNav";
import NavLinks from "@/components/NavLinks";
import Settings from "@/components/Settings";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Varia Portfolio",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className + " flex h-screen"}>
				<nav className="hidden sm:flex xl:w-1/6 md:w-1/3 flex-col justify-between p-10 border border-gray-300 shrink-0">
					<AnimatedLogo />
					<NavLinks />
					<p className="text-center text-sm">
						© 2024 Varia. All Rights Reserved.
					</p>
				</nav>
				<main className="bg-slate-200 grow p-10">{children}</main>
				<Settings />
				<MobileNav />
			</body>
			<Script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js" />
		</html>
	);
}
